trigger:
  - '*'

pr:
  - '*'

jobs:
  - job: buildAndTest
    strategy:
      matrix:
        linux:
          imageName: "ubuntu-18.04"
        mac:
          imageName: "macos-10.14"
        windows:
          imageName: "windows-2019"
      maxParallel: 3
    timeoutInMinutes: 10
    pool:
      vmImage: $(imageName)
    steps:
      - bash: |
          set -e
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DNPLOG_JUNIT_REPORTER=nplog-test.xml ..
          cmake --build . --clean-first --config Release
          ctest -C Release
      - task: PublishTestResults@2
        inputs:
            testResultsFormat: 'JUnit'
            testResultsFiles: '**/nplog-test.xml'
            testRunTitle: 'Test results'
            mergeTestResults: true
